name: mousebrain
favicon: null
layout_spectrum: 0.22705
typography_spectrum: 0.23372
title: Works by Peter Gikandi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b60024'
    - '#3f0e23'
    - '#ff1d40'
    - '#000000'
    - '#103c35'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
